### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Spanni26** [trac-hacks/trac-subtickets-plugin#22]
Hello,

I tried to install the recent subtickt on a trac 1.0
Building the Plugin works fine, copied it into the Plugin directory, added the entries in trac.ini  at the compnentents part.
But, when upgrading the trac environment, I've got:

 trac-admin /mnt/projekt/pm32/sg_age/trac upgrade
Fehler: KeyError: 'tracsubtickets/locale'

Don't know if its an issue or a installation problem.

**Comment by rjollos** [comment]
This is a standard problem when Babel is not installed. Workaround is to install Babel. I've created a pull request to fix the issue.
