### ISSUE TITLE
Link to existing tickets?

### ISSUE THREAD

**Issue by MisterVapor** [trac-hacks/trac-subtickets-plugin#25]
It's not clear whether you can link to an existing ticket or not with this plugin.  I know you can create a sub ticket but can you select from an existing ticket to make a sub ticket?

**Comment by thenor57** [comment]
You can. Simply enter a parent ticket's id in the parents field of an (existing) ticket. Note that the parents is plural - a ticket may have more than one parent.

**Comment by MisterVapor** [comment]
Thank you for the quick response.  One of our SA's attempted to install the plugin using python setup.py bdist_egg.  However, midway through the install, she received an error...

**_byte-compiling build/bdist.linux-x86_64/egg/tracsubtickets/web_ui.py to web_ui.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/tracsubtickets/web_ui.py', 282, 44, '                    inh  = {f: ticket[f] for f in opt_inherit}\n'))_**

What is this error and how do we fix it?

**Comment by rjollos** [comment]
You'll need to use Python 2.7.
