### ISSUE TITLE
Revisiting prior issue

### ISSUE THREAD

**Issue by MisterVapor** [trac-hacks/trac-subtickets-plugin#26]
I posted a question yesterday and received a response then my question was promptly closed.  So, I'm creating another post in case the notification does not occur with my prior post...

One of our SA's attempted to install the plugin using python setup.py bdist_egg. However, midway through the install, she received an error...

byte-compiling build/bdist.linux-x86_64/egg/tracsubtickets/web_ui.py to web_ui.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/tracsubtickets/web_ui.py', 282, 44, ' inh = {f: ticket[f] for f in opt_inherit}\n'))

What is this error and how do we fix it?

**Comment by rjollos** [comment]
You'll need to use Python 2.7.

**Comment by MisterVapor** [comment]
Thanks for the quick reply.  I think we're using 2.6.  We'll get it updated and go from there.

Thanks!!
