### ISSUE TITLE
Trac 1.3 compatibility issue

### ISSUE THREAD

**Issue by pcelba** [trac-hacks/trac-subtickets-plugin#28]
When starting Trac 1.3.2 following errors appear in the log:

```
tracsubtickets.api": ImportError: cannot import name TicketNotifyEmail
tracsubtickets.web_ui": ImportError: cannot import name TicketNotifyEmail
```

And that's not the last compatibility problem... I've been trying some work around with no success.

**Comment by rjollos** [comment]
The old notification system was removed in Trac 1.3.1. The plugin will need to be adapted to use the new notification system.

**Comment by thenor57** [comment]
Will look at it. Can you point to an example of use of the new interface?

BR Theodor

**Comment by pcelba** [comment]
Thanks for the quick reaction guys! 
This plugin works for me after two tweaks - notifications commented out and db update (after plugin enabling) done manually. The output (subtickets tree below the ticket description) also needs to tune styles up but this is absolutely unknown field to me.
I am attempting to install all plugins of our current Trac 1.0 to the version 1.3 and it seems I have to learn a lot more than a few Python commands...

**Comment by rjollos** [comment]
> Can you point to an example of use of the new interface?

The main example are in the Trac source code, such as `trac.ticket.web_ui`.
