### ISSUE TITLE
Batch Modify Module not working if I have enabled subticket plugin

### ISSUE THREAD

**Issue by extjmsierra** [trac-hacks/trac-subtickets-plugin#29]
I am using trac 1.2.2 and I am trying to show the commit log in tickets (I use BatchModifyModule for this) but I need also to show child and parents tickets. But if I enable the subticket plugin, the BatchModifyModule is not working and I don't know why.

Any sugestion?

I had try with subticket plugin 0.5.3 and 0.5.4, but no one working.

Trac does not display error.

**Comment by thenor57** [comment]
I propose that instead you use the XML-RPC plugin for this. It is a really nice plugin with a much more general functionality worth learning. Simply update the parents attribute; you can supply a comma-separated list if you have multiple parents.

I think that I'll withdraw the batchmodifymodule entirely rather than fix the error and add this proposal to the documentation.

**Comment by extjmsierra** [comment]
@thenor57 I am using XML-RPC for other purposes, but in this case, I need to show parent, childs and in the same ticket the commit history in the ticket show (xxx/trac/ticket/#1).

I was using the two plugins (Old BatchModify plugins and subticket plugin) in trac 0.11 and it works, but in trac 1.2.2 they have a colision. I don't know how I can do in order to fix it.

**Comment by thenor57** [comment]
OK, I'll take a look, but I'll not have time until next week.

I suspect that the reason is lack of backwards compatibility in the database interface introduced with Trac 1.2. In the meantime, please send the precise error message/stack dump  you see when you run the module.

**Comment by extjmsierra** [comment]
Hi. Sorry for the inconvenience, we have already encountered the problem. Basically we had not exported the environment variable PYTHON_EGG_CACHE and after that, it works.

Thank you very much
