### ISSUE TITLE
Please publish on PyPI

### ISSUE THREAD

**Issue by Massimo-B** [trac-hacks/trac-subtickets-plugin#30]
Please publish the plugin on [PyPI](https://pypi.org).

**Comment by thenor57** [comment]
Will do - but need to learn how-to first :-)  But trac-backlog will be first in my queue since an older version is already on PyPi

**Comment by rjollos** [comment]
Published to https://pypi.org/project/TracSubTickets.

@thenor57 I can add you as maintainer to PyPI. Do you have an account?

**Comment by rjollos** [comment]
Release steps documented.

**Comment by thenor57** [comment]
Yes, please add me as maintainer. My account name is 'thenor' - which is
also used for TracBacklog.

BR Theodor

**Comment by rjollos** [comment]
Add thenor to PyPI project.
